apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  alerts.yml: |
    groups:
      - name: sre-app-alerts
        interval: 30s
        rules:
          - alert: HighErrorRate
            expr: |
              (sum(rate(http_requests_total{kubernetes_namespace="sre-app",status=~"5.."}[5m])) 
              / 
              sum(rate(http_requests_total{kubernetes_namespace="sre-app"}[5m]))) * 100 > 5
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "High error rate detected in SRE app"
              description: "Error rate is {{ $value | humanizePercentage }}"
          
          - alert: HighLatency
            expr: |
              histogram_quantile(0.95, 
                sum(rate(http_request_duration_seconds_bucket{kubernetes_namespace="sre-app"}[5m])) by (le)
              ) > 1
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High latency detected in SRE app"
              description: "P95 latency is {{ $value }}s (threshold: 1s)"
          
          - alert: PodsDown
            expr: absent(up{kubernetes_namespace="sre-app"}) or count(up{kubernetes_namespace="sre-app"} == 0) > 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Application pods are down or missing"
              description: "No healthy pods found in sre-app namespace"

          - alert: HealthCheckFailing
            expr: up{kubernetes_namespace="sre-app", job="kubernetes-pods"} == 0
            for: 30s
            labels:
              severity: critical
            annotations:
              summary: "Health check failing"
              description: "Pod {{ $labels.kubernetes_pod_name }} health check is failing in namespace {{ $labels.kubernetes_namespace }}"
