apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: ghcr.io/YOUR_USERNAME/YOUR_REPO/sre-app
    newName: ghcr.io/dtc77ai/sre-showcase/sre-app
    newTag: latest
